# Generated by Django 5.0.6 on 2024-06-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCRUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='heading',
            field=models.CharField(default='hh', max_length=100),
            preserve_default=False,
        ),
    ]
