# Generated by Django 5.0.6 on 2024-06-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCRUD', '0002_post_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
    ]
